sourceCompatibility = 8

dependencies {
    implementation project(':core')
    compileOnly 'org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT'
}

jar {
    // Prevent duplicate files when you also include :core output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    archiveFileName = "OGUI-${project.version}.jar"
    from { project(':core').sourceSets.main.output }
}

signing {
    required = false
}
